import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/sass/app.scss',
                'resources/js/app.js',
                'resources/css/login-style.css',
                'resources/css/main-style.css',
                'resources/css/forms.css',
                'resources/css/bookings-style.css',
                'resources/css/rooms-style.css',
                'resources/css/guests-style.css',
                'resources/css/additional-services-style.css',
                'resources/css/rooms-properties-style.css',
                'resources/css/employees-style.css',
                'resources/css/users-style.css',
                'resources/css/dashboard-style.css',
                'resources/js/booking/index.js',
                'resources/js/booking/search.js',
                'resources/js/booking/show.js',
                'resources/js/booking/calculate_price.js',
                'resources/js/rooms/index.js',
                'resources/js/rooms/show.js',
                'resources/js/rooms/search.js',
                'resources/js/guests/index.js',
                'resources/js/guests/edit.js',
                'resources/js/guests/search.js',
                'resources/js/guests/create.js',
                'resources/js/guests/show.js',
                'resources/js/employees/index.js',
                'resources/js/users/index.js',
                'resources/js/dashboard/income.js',
                'resources/js/dashboard/rooms.js',
                'resources/js/dashboard/rooms_availability.js',
                'resources/js/dashboard/bookings.js',
                'resources/js/additional_services/index.js',
                'resources/js/rooms/properties/index.js',
                'resources/admin-lte-4.0/css/adminlte.css',
                'resources/admin-lte-4.0/js/adminlte.js',
            ],
            refresh: true,
        }),
    ],
});
